name: chefin
description: A new Flutter project.

# Add version and environment as needed
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3
  video_player: ^2.2.18
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# Other configurations (if any)
flutter:
  uses-material-design: true
